name: Build RouterOS Container Image

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t my-nginx:arm64 \
            --load .

      - name: Save image to tar
        run: |
          docker save my-nginx:arm64 -o my-nginx.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-nginx-tar
          path: my-nginx.tar
